name: delulufy_v1
description: "A new Flutter project."
publish_to: 'none' # This is a private project
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.1
  google_fonts: ^4.0.4
  http: ^0.13.6
  youtube_explode_dart: ^1.12.0
  cached_network_image: ^3.3.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/icon.png
    - assets/sounds/intro.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/icon.png

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.png
  android: true
  ios: true
  fullscreen: true
