name: Build Unsigned APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' # or your desired version

      - name: Install dependencies
        run: flutter pub get

      - name: Build unsigned APK
        run: flutter build apk --debug

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
